### ISSUE TITLE
mm-table on common pages not allowed

### ISSUE THREAD

**Issue by DavidBruchmann** [lorenzulrich/irreforeignselectordemo#1]
having tried the example I get an errormessage:

```
1: Attempt to insert record on page 'Home' (2) where this table, tx_irreforeignselectordemo_address_city_mm, is not allowed
```

**Comment by DavidBruchmann** [comment]
I saved the records in a folder and can assign the relations, but it's not shown in frontend

**Comment by DavidBruchmann** [comment]
Assigning the folder with the addresses and cities as Record Storage Page in the page where the plugin is inserted solves the problem.
Thanks for the nice example.

**Comment by lorenzulrich** [comment]
You're welcome!
